name: Markdown link checker

on:
  pull_request:
    types:
      - review_requested
    paths:
      - '**.md'
      - './LICENSE'
  push:
    paths:
      - '**.md'
      - './LICENSE'

concurrency: 
  group: markdown-link-check-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.14
        with:
          use-quiet-mode: 'yes'
          folder-path: 'engine, examples/apps, examples/projects, network, test, tool_services, .github'
          file-path: './README.md, ./LICENSE'
          config-file: '.github/workflows/mlc_config.json'
